version: "3.3"
services:
  postgreSQL:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  rest:
    build: rest
    restart: always
    depends_on: 
      - postgreSQL
    ports:
      - "9188:9188"